# Generated by Django 6.0.4 on 2026-04-14 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(help_text='Ej: 0001-00000001', max_length=50, unique=True, verbose_name='Número de comprobante')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento total')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('DEVOLUCION_PARCIAL', 'Devolución parcial'), ('DEVOLUCION_TOTAL', 'Devolución total')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (vendedor)')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de devolución')),
                ('motivo', models.TextField(help_text='Ej: Producto defectuoso, cliente no conforme, error de cobro', verbose_name='Motivo de devolución')),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total devuelto al cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('RECHAZADA', 'Rechazada')], default='PROCESADA', max_length=20, verbose_name='Estado')),
                ('metodo_reembolso', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de reembolso')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que procesó la devolución')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta', verbose_name='Venta original')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario al momento de la venta')),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento por unidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal de la línea')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='inventario.productovariante', verbose_name='Variante vendida')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad devuelta')),
                ('subtotal_devuelto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto devuelto por esta línea')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion', verbose_name='Devolución')),
                ('venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_detalle', to='ventas.ventadetalle', verbose_name='Línea de venta original')),
            ],
            options={
                'verbose_name': 'Detalle de devolución',
                'verbose_name_plural': 'Detalles de devolución',
            },
        ),
    ]
