# Generated by Django 6.0.4 on 2026-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_clp_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagos',
            field=models.JSONField(blank=True, default=list, help_text='Lista: [{"metodo": "EFECTIVO", "monto": 5000}, ...]', verbose_name='Detalle de pagos'),
        ),
    ]
