# Generated by Django 6.0.4 on 2026-04-20 22:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_productovariante_foto'),
        ('ventas', '0003_venta_pagos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón social')),
                ('rut', models.CharField(blank=True, default='', help_text='Ej: 76.123.456-7', max_length=20, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, default='', max_length=200, verbose_name='Persona de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de factura')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Factura de compra'), ('VENTA', 'Factura de venta')], max_length=10, verbose_name='Tipo')),
                ('subtotal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (neto)')),
                ('impuesto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IVA 19%')),
                ('total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('referencia_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ventas.venta', verbose_name='Venta POS vinculada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Solo para facturas de compra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_raw', models.CharField(blank=True, default='', max_length=500, verbose_name='Descripción (texto original)')),
                ('codigo_barras_raw', models.CharField(blank=True, default='', max_length=100, verbose_name='Código de barras (texto original)')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('subtotal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal línea')),
                ('precio_costo_snapshot', models.IntegerField(default=0, help_text='Costo al momento de la factura, no se actualiza retroactivamente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de costo (snapshot)')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_detalle', to='inventario.productovariante', verbose_name='Variante vinculada')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'indexes': [models.Index(fields=['variante'], name='idx_factdet_variante')],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ocr_documentos/%Y/%m/', verbose_name='Archivo original')),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del archivo')),
                ('tipo_archivo', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPEG'), ('PNG', 'PNG')], default='PDF', max_length=5, verbose_name='Tipo de archivo')),
                ('tamano_bytes', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de procesar'), ('PROCESANDO', 'Procesando OCR'), ('PROCESADO', 'Procesado — pendiente de revisión'), ('CONFIRMADO', 'Confirmado por usuario'), ('ERROR', 'Error en procesamiento')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('texto_raw', models.TextField(blank=True, default='', verbose_name='Texto extraído (OCR crudo)')),
                ('datos_extraidos', models.JSONField(blank=True, default=dict, help_text='JSON: {numero_factura, proveedor, productos: [{descripcion, codigo, cantidad, precio, confianza, match_tipo, variante_id}]}', verbose_name='Datos estructurados extraídos')),
                ('confianza_global', models.IntegerField(default=0, help_text='0-100, promedio de confianza de todos los campos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Confianza global (%)')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de errores: [{campo, mensaje, tipo}]', verbose_name='Errores de procesamiento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('factura_generada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_origen', to='facturacion.factura', verbose_name='Factura generada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que subió')),
            ],
            options={
                'verbose_name': 'Procesamiento de documento',
                'verbose_name_plural': 'Procesamientos de documentos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'usuario', '-creado_en'], name='idx_procdoc_est_usr_fch'), models.Index(fields=['-creado_en'], name='idx_procdoc_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha', 'tipo', 'estado'], name='idx_fact_fecha_tipo_est'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['tipo', '-fecha'], name='idx_fact_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='idx_fact_estado'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='idx_fact_numero'),
        ),
    ]
