# Generated by Django 6.0.4 on 2026-04-14 16:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='EAN-13, EAN-8, UPC-A, QR, o código personalizado', max_length=100, unique=True, verbose_name='Código de barras')),
                ('tipo', models.CharField(choices=[('EAN-13', 'EAN-13'), ('EAN-8', 'EAN-8'), ('UPC-A', 'UPC-A'), ('QR', 'QR Code'), ('INTERNO', 'Código Interno'), ('OTRO', 'Otro')], default='EAN-13', max_length=50, verbose_name='Tipo de código')),
                ('principal', models.BooleanField(default=False, help_text='Si hay múltiples códigos, indica cuál es el principal', verbose_name='Es principal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de barras',
                'verbose_name_plural': 'Códigos de barras',
                'ordering': ['-principal', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso de mercadería'), ('VENTA', 'Venta'), ('DEVOLUCION_CLIENTE', 'Devolución de cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución a proveedor'), ('AJUSTE_POSITIVO', 'Ajuste positivo (inventario)'), ('AJUSTE_NEGATIVO', 'Ajuste negativo (inventario)'), ('INICIAL', 'Carga inicial')], max_length=30, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(help_text='Positivo = entrada, Negativo = salida', verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.IntegerField(verbose_name='Stock posterior')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo / Observación')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, default='', max_length=100, verbose_name='Categoría')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rojo, Grande, Vainilla', max_length=100, verbose_name='Nombre de variante')),
                ('sku', models.CharField(blank=True, help_text='Se auto-genera si se deja vacío', max_length=100, unique=True, verbose_name='SKU interno')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de costo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['producto__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en stock')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Se emitirá alerta cuando el stock baje de este valor', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo (alerta)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
