# Generated by Django 6.0.4 on 2026-04-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='referencia_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.devolucion', verbose_name='Devolución relacionada'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='referencia_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.venta', verbose_name='Venta relacionada'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento'),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.productovariante', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='codigobarras',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barra', to='inventario.productovariante', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.productovariante', verbose_name='Variante'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'nombre')},
        ),
    ]
