# Generated by Django 6.0.4 on 2026-04-14 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codigobarras',
            index=models.Index(fields=['codigo'], name='idx_codigobarras_codigo'),
        ),
        migrations.AddIndex(
            model_name='codigobarras',
            index=models.Index(fields=['variante', 'principal'], name='idx_codigobarras_variante_principal'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['variante', '-creado_en'], name='idx_movimiento_variante_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo', '-creado_en'], name='idx_movimiento_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['-creado_en'], name='idx_movimiento_fecha'),
        ),
    ]
