# Generated by Django 6.0.4 on 2026-04-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codigobarras',
            new_name='idx_cb_codigo',
            old_name='idx_codigobarras_codigo',
        ),
        migrations.RenameIndex(
            model_name='codigobarras',
            new_name='idx_cb_variante_pri',
            old_name='idx_codigobarras_variante_principal',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='idx_mov_variante_fecha',
            old_name='idx_movimiento_variante_fecha',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='idx_mov_tipo_fecha',
            old_name='idx_movimiento_tipo_fecha',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='idx_mov_fecha',
            old_name='idx_movimiento_fecha',
        ),
    ]
