# Generated by Django 6.0.4 on 2026-04-14 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_fix_index_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='precio_costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de costo (CLP)'),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta (CLP)'),
        ),
    ]
