# Generated by Django 6.0.4 on 2026-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_clp_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/', verbose_name='Foto del producto'),
        ),
    ]
